---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: db
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
