---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-potatov-velocity-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
