---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-potatov-velocity
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      mc-potatov-velocity:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          mc-potatov-velocity:
            env:
              TZ: "America/New_York"
              TYPE: VELOCITY
              ICON: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png"
            image:
              repository: itzg/mc-proxy
              tag: latest
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: "${SVC_MC_CADDR}"
        externalTrafficPolicy: Local
        controller: mc-potatov-velocity
        ports:
          game:
            port: 25565
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false

    persistence:
      config:
        enabled: true
        existingClaim: mc-potatov-velocity-v1
        globalMounts:
          - path: /server
