---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-potatov-velocity
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    nodeSelector:
      kubernetes.io/hostname: duck
    minecraftProxy:
      # This can be one of "BUNGEECORD", "WATERFALL", "VELOCITY", "CUSTOM"
      type: VELOCITY
      velocityVersion: 3.1.1
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_CADDR}"
      externalTrafficPolicy: Local
      configFilePath: /server/velocity.toml
      config: |-
        config-version = "2.7"
        bind = "0.0.0.0:25577"
        motd = "Hello from Velocityyyyyyy!"
        show-max-players = 50000
        player-info-forwarding-mode = "modern"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-potatov-velocity-v1
