---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: factorio2
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      factorio:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          factorio:
            env:
              TZ: "America/New_York"
              SAVE_NAME: factorio2-24mc
              BIND: "0.0.0.0"
            image:
              repository: factoriotools/factorio
              tag: 2.0.33
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: "${SVC_FACTORIO2_ADDR}"
        externalTrafficPolicy: Local
        controller: factorio2
        ports:
          gameudp:
            port: 34197
            protocol: UDP
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false

    persistence:
      config:
        enabled: true
        existingClaim: factorio2-v1
        globalMounts:
          - path: /factorio
