---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.3.1
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
        subPath: data
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: home-assistant-sharedip
        loadBalancerIP: "${SVC_HOMEASSISTANT_ADDR}"
        ports:
          http:
            port: 8123
          homekittcp:
            enabled: true
            port: 21063
            targetPort: 21063
      otherudp:
        enabled: true
        primary: false
        name: home-assistant-udp
        annotations:
          metallb.universe.tf/allow-shared-ip: home-assistant-sharedip
        type: LoadBalancer
        loadBalancerIP: "${SVC_HOMEASSISTANT_ADDR}"
        ports:
          homekitudp:
            enabled: true
            port: 5353
            targetPort: 5353
            protocol: UDP
