---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: phybros-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://phybros.github.io/helm-charts/
  timeout: 3m
