---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
