apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 8Gi
