---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-potato-smp-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
