---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunshine-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
