---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sunshine
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      sunshine:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          sunshine:
            env:
              TZ: "America/New_York"
              DISPLAY_SIZEW: "1920"
              DISPLAY_SIZEH: "1080"
              DISPLAY_REFRESH: "60"
              DISPLAY_DPI: "96"
              DISPLAY_CDEPTH: "24"
              VIDEO_PORT: "DFP"
              PASSWD: "sunshine"
            image:
              repository: ghcr.io/selkies-project/nvidia-glx-desktop
              tag: latest
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: "${SVC_SUNSHINE_ADDR}"
        externalTrafficPolicy: Local
        controller: sunshine
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: sunshine-v1
        globalMounts:
          - path: /sunshine
  
    podSecurityContext:
      # Hardware acceleration using an Intel iGPU w/ QuickSync
      # These IDs below should be matched to your `video` and `render` group on the host
      # To obtain those IDs run the following grep statement on the host:
      # $ cat /etc/group | grep "video\|render"
      # video:x:44:
      # render:x:109:
      supplementalGroups:
      - 44
      - 109
    resources:
      requests:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
