---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: factorio
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      factorio:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          factorio:
            env:
              TZ: "America/New_York"
              SAVE_NAME: factorio-24mc
              BIND: "0.0.0.0"
            image:
              repository: factoriotools/factorio
              tag: 1.1.110
    service:
      app:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: factorio-sharedip
        loadBalancerIP: "${SVC_FACTORIO_ADDR}"
        controller: factorio
        ports:
          gametcp:
            port: 27015
          gameudp:
            port: 34197
            protocol: UDP
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false

    persistence:
      config:
        enabled: true
        existingClaim: factorio-v1
        globalMounts:
          - path: /factorio
