---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iperf3
  namespace: networking
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      iperf3:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          iperf3:
            env:
              TZ: "America/New_York"
            image:
              repository: networkstatic/iperf3
              tag: latest
            args:
              - -s
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: "${SVC_IPERF_ADDR}"
        externalTrafficPolicy: Local
        controller: iperf3
        ports:
          iperf:
            port: 5201
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false
