---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 10.6.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gitea/gitea
      tag: 1.22.4
    service:
      ssh:
        type: LoadBalancer
        port: 22
        loadBalancerIP: "${SVC_GITEA_SSH_ADDR}"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-forward-auth@kubernetescrd"
      hosts:
        - host: "code.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "code.${SECRET_DOMAIN}"
          secretName: "gitea-tls"
    persistence:
      enabled: true
      mount: true
      create: false
      claimName: gitea-config-v1
    gitea:
      config:
        APP_NAME: "24Mc Code"
        server:
          PROTOCOL: http
          DOMAIN: "code.${SECRET_DOMAIN}"
          ROOT_URL: "https://code.${SECRET_DOMAIN}"
        service:
          DISABLE_REGISTRATION: "true"
        security:
          SECRET_KEY: "${SECRET_GITEA_SECRET}"
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            password: "${SECRET_GITEA_PG_PASSWORD}"
            database: gitea
            username: gitea
          service:
            ports:
              postgresql: 5432
      primary:
        persistence:
          enabled: true
          existingClaim: gitea-db-v1
          subPath: data
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 512m
            memory: 1024Mi
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 9.6.24-debian-10-r44
    redis:
      enabled: false
    redis-cluster:
      enabled: true
      usePassword: false
      cluster:
        nodes: 3
        replicas: 0
      redis:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 512m
            memory: 1024Mi
