---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-db
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 16.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  targetNamespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: paperless-postgresql
    image:
      repository: bitnami/postgresql
      tag: 15.2.0
    auth:
      database: paperless-ngx
      username: paperless-ngx
      password: paperless-ngx
    primary:
      persistence:
        enabled: true
        existingClaim: paperless-db-v1
