---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: backup-system
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: backube-charts
        namespace: flux-system
      interval: 30m
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
