---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-lobby-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: rook-ceph-block
