---
apiVersion: v1
kind: Secret
metadata:
   name: restic-mc-potatov-lobby
   namespace: games
type: Opaque
stringData:
   RESTIC_REPOSITORY: "${SECRET_RESTIC_REPO}/mc-potatov-lobby"
   RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
   AWS_ACCESS_KEY_ID: ${SECRET_RESTIC_AWS_ACCESS_KEY_ID}
   AWS_SECRET_ACCESS_KEY: ${SECRET_RESTIC_AWS_SECRET_ACCESS_KEY}

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: replication-source-mc-potatov-lobby
   namespace: games
spec:
   sourcePVC: mc-potatov-lobby-v1
   trigger:
      schedule: "30 07 * * *"
   restic:
     pruneIntervalDays: 7
     repository: restic-mc-potatov-lobby
     cacheStorageClassName: local-path
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     copyMethod: Snapshot
