---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vintagestory
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      vintagestory:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          vintagestory:
            image:
              repository: devidian/vintagestory
              tag: latest
            env:
              TZ: "America/New_York"
              VS_DATA_PATH: /gamedata
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: "${SVC_VINTAGESTORY_ADDR}"
        externalTrafficPolicy: Local
        controller: vintagestory
        ports:
          game:
            port: 42420
          gameudp:
            port: 42420
            protocol: UDP
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false

    persistence:
      config:
        enabled: true
        existingClaim: vintagestory-v1
        globalMounts:
          - path: /gamedata
