---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: duck
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
    controllers:
      filebrowser:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          filebrowser:
            env:
              TZ: "America/New_York"
              FB_DATABASE: /config/filebrowser.db
              FB_LOG: stdout
              FB_PORT: &port 8000
              FB_BASEURL: /survival
            image:
              repository: filebrowser/filebrowser
              tag: v2.32.0

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_FILEBROWSER_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: fb-sharedip
        controller: filebrowser
        ports:
          http:
            port: *port        
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false

    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-v1
      minecraftdata:
        enabled: true
        existingClaim: mc-potatov-v1
        globalMounts:
          - path: /srv

