---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-school-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
