---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-school
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 6Gi
    minecraftServer:
      levelSeed: potatocraft4
      worldSaveName: potatocraft4
      eula: "TRUE"
      type: "PAPER"
      version: "1.21.1"
      pvp: "default"
      gameMode: survival
      overrideServerProperties: true
      viewDistance: 10
      spawnProtection: 4
      enableCommandBlock: true
      icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png"
      difficulty: "normal"
      motd: "\u00a7f\u00a7l-POTATOCRAFT IV-\u00a72"
      memory: 5120M
      serviceType: LoadBalancer
      ops: "phybros,gimgam5000"
      loadBalancerIP: "${SVC_MC_SADDR}"
      externalTrafficPolicy: Local
      extraPorts:
      rcon:
        enabled: true
        port: 25575
        password: "${SECRET_MC_RCON_PASSWORD}"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-school-v1
