---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-sre-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block
