---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 128Mi
