---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 100Gi
