---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
  values:
    controllers:
      ollama:
        replicas: 3 # 1 per node
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: intelanalytics/ipex-llm-inference-cpp-xpu
              tag: 2.3.0-SNAPSHOT
            command:
              - /bin/sh
              - -c
              - mkdir -p /llm/ollama && cd /llm/ollama && init-ollama && exec ./ollama serve
            securityContext:
              privileged: true
            env:
              OLLAMA_MODELS: &modelPath /models
              no_proxy: localhost,127.0.0.1
              OLLAMA_HOST: 0.0.0.0
              DEVICE: Arc
              OLLAMA_INTEL_GPU: true
              OLLAMA_NUM_GPU: 999
              ZES_ENABLE_SYSMAN: 1
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 16Gi
                gpu.intel.com/i915: 1
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - "{{ .Release.Name }}"
    service:
      app:
        ports:
          http:
            port: &port 11434
    persistence:
      ollama:
        existingClaim: ollama-config-v1
        globalMounts:
          - path: *modelPath
            subPath: models
          - path: /root/.ollama
            subPath: config
      dri:
        type: hostPath
        hostPath: /dev/dri
