---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: seafile
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://phybros.github.io/helm-charts
      chart: seafile
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: phybros-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: seafileltd/seafile-mc
      tag: 11.0.2
    env:
      SEAFILE_SERVER_HOSTNAME: "files.${SECRET_DOMAIN}"
      SEAFILE_ADMIN_EMAIL: "${SECRET_MY_EMAIL}"
      SEAFILE_ADMIN_PASSWORD: "${SECRET_SEAFILE_ADMIN_PASSWORD}"
      DB_HOST: seafile-mariadb
      DB_ROOT_PASSWD: seafilerootpass

    persistence:
      shared:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.201
            path: "/duckpond/seafile"
        mountPath: /shared

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "files.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "files.${SECRET_DOMAIN}"
            secretName: "seafile-tls"

    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          existingClaim: seafile-db-v1
