---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
configMapGenerator:
  - name: nginx-conf
    namespace: default
    files:
      - nginx.conf
generatorOptions:
  disableNameSuffixHash: true
