---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: 4.1.1
